# netlify configuration
[build]
base = "site/"
publish = "site/public/"

[build.environment]
HUGO_VERSION = "0.53"

[context.production.environment]
# this controls our robots.txt
HUGO_ENV = "production"
