# this config file contains all config fields with comments
apiVersion: kind.sigs.k8s.io/v1alpha1
kind: Config

# TODO(bentheelder): add cluster wide patches or fix this to include
# a single node
# patch the generate kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1alpha3
  kind: ClusterConfiguration
  networking:
    serviceSubnet: 10.0.0.0/16

# patch it further using a json 6902 patch
kubeadmConfigPatchesJson6902:
- group: kubeadm.k8s.io
  version: v1alpha3
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServerCertSANs/-
      value: my-hostname
