title = "kind"
languageCode = "en-us"

# we use this to disable indexing for the non-production build
enableRobotsTXT = true

# this allows us to show the source commit in the footer
enableGitInfo = true

# syntax highlighting options
pygmentsCodeFences = true
pygmentsStyle = "tango"

# enable hugo's menu system for the site, name the primary menu
sectionPagesMenu = "main"
# menu entries
[menu]
  [[menu.main]]
    identifier = "ome"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "user"
    name = "User Guide"
    title = "User Guide"
    weight = 2
   [[menu.main]]
    parent = "user"
    identifier = "user-quick-start"
    name = "Quick Start"
    title = "Quick Start"
    url = "/docs/user/quick-start"
    weight = 1
  [[menu.main]]
    parent = "user"
    identifier = "user-known-issues"
    name = "Known Issues"
    title = "Known Issues"
    url = "/docs/user/known-issues"
    weight = 2
  [[menu.main]]
    identifier = "roadmap"
    name = "Roadmap"
    title = "Roadmap"
    url = "/docs/roadmap/"
    weight = 4
  [[menu.main]]
    identifier = "design"
    name = "Design"
    title = "Design"
    url = "/docs/design/"
    weight = 5
  [[menu.main]]
    parent = "design"
    identifier = "design-initial"
    name = "Initial"
    title = "Initial"
    url = "/docs/design/initial"
    weight = 1
  [[menu.main]]
    parent = "design"
    identifier = "design-principles"
    name = "Principles"
    title = "Principles"
    url = "/docs/design/principles"
    weight = 1
  [[menu.main]]
    parent = "design"
    identifier = "base-image"
    name = "Base Image"
    title = "Base Image"
    url = "/docs/design/base-image/"
  [[menu.main]]
    parent = "design"
    identifier = "node-image"
    name = "Node Image"
    title = "Node Image"
    url = "/docs/design/node-image/"
  [[menu.main]]
    identifier = "devel"
    name = "Developer Guide"
    title = "Developer Guide"
    url = "/docs/devel/"
    weight = 6
  [[menu.main]]
    parent = "devel"
    identifier = "devel-getting-started"
    name = "Getting Started"
    title = "Getting Started"
    url = "/docs/devel/getting-started/"
    weight = 1
  [[menu.main]]
    parent = "devel"
    identifier = "project-structure"
    name = "Project Structure"
    title = "Project Structure"
    url = "/docs/devel/project-structure/"
