# See https://cloud.google.com/cloud-build/docs/build-config
options:
  substitution_option: ALLOW_LOOSE
steps:
- name: gcr.io/k8s-testimages/krte:latest-master
  env:
  entrypoint: make -C images/kindnetd push
