# this config file contains all config fields with comments
apiVersion: kind.sigs.k8s.io/v1alpha1
kind: Config

# patch the generate kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1alpha2
  kind: MasterConfiguration
  networking:
    serviceSubnet: 10.0.0.0/16
  kubeletConfiguration:
    baseConfig:
      clusterDNS:
      - 10.0.0.10

# patch it further using a json 6902 patch
kubeadmConfigPatchesJson6902:
- group: kubeadm.k8s.io
  version: v1alpha2
  kind: MasterConfiguration
  patch: |
    - op: add
      path: /apiServerCertSANs/-
      value: my-hostname

# control plane node config
controlPlane:
  # node lifecycle hooks
  nodeLifecycle:
    # commands run before systemd boots
    preBoot:
    - name: "should fail"
      command: [ "yep-not-a-real-command" ]
    # commands run before kubeadm init
    preKubeadm: []
    # commands run after kubeadm init
    postKubeadm: []
    # commands run after all other setup on the node
    postSetup:
    - name: "list containers"
      command: [ "docker", "ps" ]
      # this command cannot fail, or else kind will fail during create
      mustSucceed: true
